export const policyData = `
<h1 dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt; text-align: center;"><strong><span font-size:="" font-weight:="" new="" style="color: rgb(0, 0, 0); font-family: " text-align:="" times="" white-space:="">Chamm Terms of Use</span></strong></h1>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:8pt;text-align: justify;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">These terms govern your use of the mentori.vn website and the products, features and services Mentori offers, unless we expressly state that separate terms apply.</span></span></span></p>
<h2 dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 12pt; margin-bottom: 0pt;"><span style="font-size:20px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">I. Chamm Services, Chamm Software</span></span></span></h2>
<ul dir="ltr">
<li style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; margin-left: 30pt; text-align: justify;">
<p><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Use of Chamm Services on a Product:</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"> To use certain Chamm Services on a Product, you must have your own Chamm.com account, be logged in to your account on the Product, and have a valid payment method associated with your account.</span></span></span></p>
</li>
<li style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 10pt; margin-left: 30pt; text-align: justify;">
<p><span style="font-size:14px;"><span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Use of the Chamm Software:</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"> Except as provided in this section, you may use the Chamm Software only on your Product. For additional terms that apply to the Chamm Software, see the Additional Chamm Software Terms contained in the Chamm.com Conditions of Use and the terms contained in the Legal section of the Settings menu of the Chamm Services on your Product or the Chamm Fire TV Remote App. Chamm Software licensed under an open source license is governed solely by the terms of that open source license.</span></span></span></span></span></span></p>
</li>
</ul>
<h2 dir="ltr" style="list-style-type: disc; font-size: 12pt; line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:20px;"><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">II. Connectivity and Availability </span></span></span></span></h2>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size:14px;"><span style="color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">1. Internet Connectivity:</span></span></strong></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span font-size:="" new="" style="background-color: transparent; color: rgb(0, 0, 0); font-family: " times="" white-space:="">Chamm Services may require an Internet connection from a third-party provider in order to use some features. In such cases, your Internet connection is subject to the fees, restrictions, terms and limitations imposed by your provider..</span><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"> </span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">2. Availability:</span></span></span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Some Chamm Services may be unavailable, vary (by product or geography, for example), be offered for a limited time, or require separate subscriptions. </span></span></span></p>
<p dir="ltr" style="list-style-type: decimal; font-size: 12pt; margin-top: 2pt; margin-bottom: 0pt;"><span style="font-size:14px;"><span><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""> </span></span></span></p>
<h2 dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 12pt; margin-bottom: 0pt;"><span style="font-size:20px;"><strong><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">III. General</span></span></strong></span></h2>
<p dir="ltr" style="list-style-type: upper-roman; font-size: 12pt; margin-top: 2pt; margin-bottom: 4pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">1. Information Received</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">The Chamm Software may provide us with information about your Product, use of the Product, and use of Digital Content, other content, and the Chamm Services (such as search queries, installed applications, viewing and usage data, available memory, log files, network diagnostics, voice information, and connectivity). Manufacturers of your Product may also provide us with similar information. Information provided to Chamm may be processed in the cloud to improve your experience and our services, and may be stored on servers outside the country in which you live. We will handle any information we receive in accordance with the Chamm.com Privacy Notice. Please visit the Settings menu of your Product if you prefer to opt out of providing certain information..</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size:14px;"><span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline;">2.&nbsp;</span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Information Provided To Others</span></span></span></strong></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">You are responsible for any information you provide to others, including third-party Digital Content providers. Use of information you provide to these third parties will be subject to any privacy notice or other terms that they may provide to you.</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">3. Changes to Chamm Services; Amendments</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""> We may change, suspend, or discontinue the Chamm Services, or any part of them, at any time without notice. We may amend any of this Agreement's terms at our sole discretion by posting the revised terms on the Chamm.com website. Your continued use of Chamm Services after the effective date of the revised Agreement constitutes your acceptance of the terms.</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span><span style="color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">4. Termination</span></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Your rights under this Agreement will automatically terminate without notice if you fail to comply with any of its terms. In case of such termination, Chamm may immediately revoke your access to the Chamm Services. Chamm's failure to insist upon or enforce your strict compliance with this Agreement will not constitute a waiver of any of its rights.</span></span></span></p>
<p dir="ltr" style="list-style-type: disc; font-size: 12pt; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size:20px;"><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span style="background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">IV. HOW TO CONTACT MENTORI WITH QUESTIONS</span></span></span></span></p>
<h2 dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span background-color:="" color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:=""If you have questions about this policy, you can contact us using the information below:</span></span></span></h2>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Email: </span><a href="mailto:youthmentor.community@gmail.com" style="text-decoration-line: none;">contact@chamm.vn</a></span></span></p>
<p dir="ltr" style="line-height: 1.2; margin-top: 0pt; margin-bottom: 8pt;"><span style="font-size:14px;"><span id="docs-internal-guid-cfcf0f1b-7fff-0981-4e13-2182d94bfe0a"><span color:="" font-variant-east-asian:="" font-variant-numeric:="" new="" times="" vertical-align:="" white-space:="">Hotline: +84 394 531 691</span></span></span></p>`
